apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.redisService.name }}
  labels:
    app: {{ .Values.redisService.labels }}
spec:
  ports:
  - port: {{ .Values.redisService.port }}
    targetPort: {{ .Values.redisService.port }}
  selector:
    app: {{ .Values.redisService.labels }}